development:
  paypal_email: gilles_1238294519_biz@me.com
  paypal_cert_id: CFJPNL63J97XY
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/websrc"

test:
  paypal_email: test@example.com
  paypal_secret: testscret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl

production:
  paypal_email: foo@example.com # todo : change for the real one
  paypal_cert_id: CFJPNL63J97XY # todo : change with the real one
  paypal_url: "https://www.paypal.com/cgi-bin/websrc"
